services:
  nixie-clock-mqtt:
    build: ./app
    container_name: nixie-clock-mqtt
    restart: unless-stopped
    env_file: ./app/.env
    environment:
      - NODE_ENV=production
    network_mode: host
